#+options: toc:nil

* exercise-13

#+toc: headlines local

** Test whether your compiler observes inline declarations.

#+begin_src lisp
  (declaim (inline single?))

  (defun single? (lst)
    (and (consp lst) (null (cdr lst))))

  (defun foo (x)
    (single? (bar x)))

  (macroexpand-1 'foo)
#+end_src

#+RESULTS:
: FOO

** Rewrite the following function...

2.Rewrite the following function to be tail-recursive. How much faster is it when compiled?
#+begin_src lisp
  (defun foo (x)
    (if (zerop x)
        0
        (+ 1 (foo (1- x)))))
#+end_src

#+RESULTS:
: FOO

#+begin_src lisp
  (defun new-foo (x)
    (labels ((tail (l a)
               (if (zerop l)
                   a
                   (tail (1- l) (1+ a)))))
      (tail x 0)))
  (time (new-foo 10000))
  (time (foo 10000))
#+end_src

#+RESULTS:
: NEW-FOO

** Add declarations to the following programs....

3.Add declarations to the following programs. How much faster can you make them?

a)The date arithmetic code in Section 5.7.([[file:section-5-7.org::*section-5-7 Example: Date Arithmetic][section-5-7 Example: Date Arithmetic]])

#+include: "../src/exercise-13-3-a.lisp" src lisp

b)The ray-tracer in Section 9.8.([[file:section-9-8.org::*section-9-8 Example: Ray-Tracing][section-9-8 Example: Ray-Tracing]])

#+include: "../src/exercise-13-3-b.lisp" src lisp

** Rewrite the breadth-first search...

4.Rewrite the breadth-first search code in Section 3.15 so that it conses as little as possible.

** Modify the binary search tree code in Section 4.7 to use pools.
[[file:section-4-7.org::*section-4-7 Example: Binary Search Trees][section-4-7 Example: Binary Search Trees]]

#+include: "../src/exercise-13-5.lisp" src lisp
