#+options: toc:nil

* exercises 3

#+toc: headlines local

** Show the following lists in box notation:

1) ~(a b (c d))~

   +-----+-----+      \ +----+----+     \ +----+-----+
   |  a  |     |-------X|  b |    |------X|    | nil |
   +-----+-----+      / +----+----+     / +--+-+-----+
                                             |
                                          +--+-+----+     \ +----+----+
                                          |  c |    +------X|  d | nil|
                                          +----+----+     / +----+----+

2) ~(a (b (c (d))))~

   +-----+----+    \ +----+----+    \ +----+----+    \ +----+----+       +----+----+       +----+----+      +----+----+
   |  a  |    |-----X|    |nil |  +--X|  b |    |-----X|    |nil |   +---+  c |    +-------+    |nil |   +--+ d  |nil |
   +-----+----+    / +--+-+----+  | / +----+----+    / +--+-+----+   |   +----+----+       +--+-+----+   |  +----+----+
                        |         |                       |          |                        |          |
                        +---------+                       +----------+                        +----------+
3) ~(((a b) c) d)~

   +----+----+       \ +----+----+  /     +----+----+   \ +----+----+  /    +----+----+     \  +----+----+
   |  a |    |--------X| b  |nil |-X------+    |    +----X|  c |nil |-X-----+    |    +------X |  d | nil|
   +----+----+       / +----+----+  \     +----+----+   / +----+----+  \    +----+----+     /  +----+----+

4) ~(a (b . c) . d)~

   +----+----+     \ +---+----+
   |  a |    +------X|   |  d |
   +----+----+     / +-+-+--+-+
                       |
                       | +---+----+
                       +-+ b |  c |
                         +---+----+

** Write a version of union that preserves the order of the elements in the original lists:

#+begin_src lisp
  (defun new-union (l1 l2)
    (reverse (remove-duplicates (reverse (append (copy-list l1) (copy-list l2))))))
#+end_src

#+RESULTS:
: NEW-UNION

** Define a function that takes a list and...

Define a function that takes a list and returns a list indicating the
number of times each (eql) element appears, sorted from most common
element to least common:

#+include: "../src/exercise-3-3.lisp" src lisp

#+RESULTS:
: OCCURRENCES

** Why does ~(member ' ( a ) ' ( ( a ) ( b ) ) )~ return nil?

** Suppose the function ~pos+~ takes a list and...

Suppose the function pos+ takes a list and returns a list of each element
plus its position:

** After years of deliberation,...

After years of deliberation, a government commission has decided that lists should be represented by using the cdr to point to the first element and the car to point to the rest of the list. Define the government versions of the following functions:

** Modify the program in Figure 3.6 to...

Modify the program in Figure 3.6 to use fewer cons cells. (Hint: Use dotted lists.)

** Define a function that takes a list and prints it in dot notation:

** Write a program to find the...

Write a program to find the ~longest~ finite path through a network represented as in Section 3.15. The network may contain cycles.
